# Generated by Django 5.2.10 on 2026-01-30 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrospective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='회고 제목', max_length=120, null=True)),
                ('content_md', models.TextField(help_text='회고 내용 (마크다운)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrospectives', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrospectives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retrospectives',
                'indexes': [models.Index(fields=['project', 'user'], name='retrospecti_project_1604fb_idx'), models.Index(fields=['created_at'], name='retrospecti_created_521842_idx')],
            },
        ),
    ]
