# Generated by Django 5.2.10 on 2026-02-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reflections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="retrospective",
            name="bookmarked",
            field=models.BooleanField(default=False, help_text="찜 여부"),
        ),
    ]
