# Generated by Django 5.2.10 on 2026-02-04 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_is_favorite_project_project_image_and_more"),
        ("reflections", "0002_retrospective_bookmarked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retrospective",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retrospectives",
                to="projects.project",
            ),
        ),
    ]
