# Generated by Django 5.2.10 on 2026-02-05 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_is_favorite_project_project_image_and_more"),
        ("reflections", "0003_alter_retrospective_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="retrospective",
            name="answers_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="질문별 답변 원본(JSON). 값은 마크다운 텍스트 문자열을 권장",
            ),
        ),
        migrations.AddField(
            model_name="retrospective",
            name="template_key",
            field=models.CharField(
                default="default",
                help_text="회고 질문 템플릿 키 (e.g., default, compact)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="retrospective",
            name="content_md",
            field=models.TextField(blank=True, default="", help_text="회고 내용 (마크다운)"),
        ),
        migrations.AddIndex(
            model_name="retrospective",
            index=models.Index(
                fields=["template_key", "created_at"],
                name="retrospecti_templat_94e10e_idx",
            ),
        ),
    ]
