# Generated by Django 5.2.10 on 2026-02-06 05:36

import apps.reflections.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reflections", "0004_retrospective_answers_json_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetrospectiveAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="첨부 이미지",
                        upload_to=apps.reflections.models.retrospective_asset_upload_to,
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="마크다운 이미지 alt 텍스트",
                        max_length=120,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "retrospective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="reflections.retrospective",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retrospective_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "retrospective_assets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["retrospective", "created_at"],
                        name="retrospecti_retrosp_f6b2dc_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="retrospecti_user_id_382b28_idx",
                    ),
                ],
            },
        ),
    ]
