# Generated by Django 5.2.10 on 2026-02-06 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reflections", "0005_retrospectiveasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="retrospectiveasset",
            name="draft_key",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="retrospectiveasset",
            name="retrospective",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="reflections.retrospective",
            ),
        ),
    ]
