# Generated by Django 5.2.10 on 2026-01-30 05:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('guides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='프로젝트 제목', max_length=120)),
                ('description', models.TextField(blank=True, help_text='프로젝트 설명', null=True)),
                ('duration_weeks', models.SmallIntegerField(default=6, help_text='프로젝트 기간 (주)', validators=[django.core.validators.MinValueValidator(1)])),
                ('target_team_size', models.SmallIntegerField(default=5, help_text='목표 팀 인원 (PM1/FE2/BE2 = 5명)')),
                ('status', models.CharField(choices=[('DRAFT', '임시저장'), ('OPEN', '모집중'), ('MATCHED', '매칭완료'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료'), ('ARCHIVED', '보관됨')], default='OPEN', help_text='프로젝트 상태', max_length=20)),
                ('starts_at', models.DateField(blank=True, help_text='시작 예정일', null=True)),
                ('ends_at', models.DateField(blank=True, help_text='종료 예정일', null=True)),
                ('region', models.CharField(blank=True, help_text='활동 지역 (오프라인 시)', max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_stage', models.ForeignKey(blank=True, help_text='현재 진행 중인 가이드 단계', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='guides.guidestage')),
                ('owner', models.ForeignKey(blank=True, help_text='프로젝트 생성자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passion_level', models.SmallIntegerField(help_text='열정 레벨 (1~4, 설문 결과)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('status', models.CharField(choices=[('APPLIED', '지원됨'), ('CANCELLED', '취소됨'), ('MATCHED', '매칭됨'), ('REJECTED', '거절됨')], default='APPLIED', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.project')),
                ('role', models.ForeignKey(help_text='지원 역할 (PM/FRONTEND/BACKEND)', on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_applications',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_status_6303d7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='projects_created_40bcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectapplication',
            index=models.Index(fields=['project', 'role', 'status'], name='project_app_project_6eb18d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectapplication',
            index=models.Index(fields=['user', 'status'], name='project_app_user_id_49508c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectapplication',
            index=models.Index(fields=['passion_level'], name='project_app_passion_afa48b_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectapplication',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='uq_project_application'),
        ),
        migrations.AddConstraint(
            model_name='projectapplication',
            constraint=models.CheckConstraint(condition=models.Q(('passion_level__gte', 1), ('passion_level__lte', 4)), name='ck_passion_level_range'),
        ),
    ]
