# Generated by Django 5.2.10 on 2026-02-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='시즌명 (예: 2026년 1월 시즌)', max_length=100)),
                ('status', models.CharField(choices=[('UPCOMING', '예정'), ('MATCHING', '팀매칭 중'), ('IN_PROJECT', '프로젝트 진행 중'), ('ENDED', '종료')], default='UPCOMING', max_length=20)),
                ('matching_start', models.DateTimeField(help_text='팀매칭 시작')),
                ('matching_end', models.DateTimeField(help_text='팀매칭 종료')),
                ('project_start', models.DateTimeField(help_text='프로젝트 시작')),
                ('project_end', models.DateTimeField(help_text='프로젝트 종료')),
                ('is_active', models.BooleanField(default=False, help_text='현재 진행 중인 시즌')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seasons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='seasons_is_acti_2e3a86_idx'), models.Index(fields=['status'], name='seasons_status_dc032e_idx')],
            },
        ),
    ]
