# Generated by Django 5.2.10 on 2026-02-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='즐겨찾기 여부'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, help_text='프로젝트 프로필 사진', null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='related_links',
            field=models.JSONField(blank=True, default=dict, help_text='관련 링크 (Notion, Figma, GitHub 등)'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_rules',
            field=models.TextField(blank=True, help_text='팀 규칙 (마크다운)', null=True),
        ),
    ]
