# Generated by Django 5.2.10 on 2026-02-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_is_favorite_project_project_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='current_stage',
        ),
    ]
