# Generated by Django 5.2.10 on 2026-02-07 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_current_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='season',
            field=models.ForeignKey(blank=True, help_text='속한 시즌', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.season'),
        ),
    ]
