# Generated by Django 5.2.10 on 2026-02-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_season_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='related_links',
            field=models.TextField(blank=True, help_text='관련 링크 (마크다운)', null=True),
        ),
    ]
