# Generated by Django 5.2.10 on 2026-02-07 13:23

from django.db import migrations


def clean_related_links(apps, schema_editor):
    """"{}" 형식의 related_links를 None으로 변환"""
    Project = apps.get_model('projects', 'Project')
    Project.objects.filter(related_links='{}').update(related_links=None)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_related_links'),
    ]

    operations = [
        migrations.RunPython(clean_related_links),
    ]
