# Generated by Django 5.2.10 on 2026-02-10 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_clean_related_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='좋아요 받은 프로젝트', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='projects.project')),
                ('user', models.ForeignKey(help_text='좋아요 누른 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='project_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_likes',
                'indexes': [models.Index(fields=['project'], name='project_lik_project_a701ec_idx'), models.Index(fields=['user'], name='project_lik_user_id_47c108_idx')],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
