# Generated by Django 5.2.10 on 2026-02-13 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectapplication',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectapplication',
            name='role',
        ),
        migrations.RemoveField(
            model_name='projectapplication',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='season',
            name='seasons_is_acti_2e3a86_idx',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='project',
            name='target_team_size',
        ),
        migrations.RemoveField(
            model_name='season',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='ProjectApplication',
        ),
    ]
