# Generated by Django 5.2.10 on 2026-01-31 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_profile_image_url_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_ban_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='남은 팀플 참여 금지 횟수'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='신고 사유')),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('APPROVED', '승인'), ('REJECTED', '거절')], default='PENDING', help_text='신고 처리 상태', max_length=10)),
                ('admin_note', models.TextField(blank=True, help_text='운영자 메모', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='처리 일시', null=True)),
                ('reported_user', models.ForeignKey(help_text='피신고자', on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(help_text='신고자', on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='reports_status_19e159_idx')],
            },
        ),
    ]
