# Generated by Django 5.2.10 on 2026-02-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_team_ban_count_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_id',
            field=models.CharField(blank=True, help_text='GitHub 아이디', max_length=39, null=True, unique=True),
        ),
    ]
