# Generated by Django 5.2.10 on 2026-02-01 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_github_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passion_level',
            field=models.SmallIntegerField(blank=True, help_text='열정 레벨 (1~4)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
