# Generated by Django 5.2.10 on 2026-02-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_passion_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='기술 이름 (Python, React 등)', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('LANGUAGE', '프로그래밍 언어'), ('FRONTEND', '프론트엔드'), ('BACKEND', '백엔드'), ('DATABASE', '데이터베이스'), ('TOOL', '개발 도구')], help_text='기술 카테고리', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tech_stacks',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='tech_stacks_categor_f30f5c_idx')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tech_stacks',
            field=models.ManyToManyField(blank=True, help_text='사용자가 보유한 기술 스택', related_name='users', to='accounts.techstack'),
        ),
    ]
