# Generated by Django 5.2.10 on 2026-02-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_techstack_user_tech_stacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='이메일 알림 수신 여부'),
        ),
    ]
