# Generated by Django 5.2.10 on 2026-02-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_email_notifications_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False, help_text='이메일 알림 수신 여부'),
        ),
    ]
