# Generated by Django 5.2.10 on 2026-02-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_email_notifications_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='category',
            field=models.CharField(choices=[('FRONTEND', '프론트엔드'), ('BACKEND', '백엔드'), ('PM', '기획')], help_text='기술 카테고리', max_length=20),
        ),
    ]
