# Generated by Django 5.2.10 on 2026-01-30 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'guide_task_progress',
            },
        ),
        migrations.CreateModel(
            name='GuideStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='단계 코드 (예: S01_KICKOFF, S02_ERD)', max_length=40, unique=True)),
                ('title', models.CharField(help_text='단계 제목', max_length=120)),
                ('description', models.TextField(blank=True, help_text='단계 설명', null=True)),
                ('order_no', models.IntegerField(default=0, help_text='정렬 순서')),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'guide_stages',
                'ordering': ['order_no'],
                'indexes': [models.Index(fields=['order_no'], name='guide_stage_order_n_5f6b90_idx'), models.Index(fields=['is_active'], name='guide_stage_is_acti_27d912_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuideCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='카드 제목', max_length=120)),
                ('content_md', models.TextField(help_text='상세 가이드 내용 (마크다운)')),
                ('order_no', models.IntegerField(default=0, help_text='정렬 순서')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(help_text='대상 역할 (PM/FRONTEND/BACKEND)', on_delete=django.db.models.deletion.CASCADE, related_name='guide_cards', to='accounts.role')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='guides.guidestage')),
            ],
            options={
                'db_table': 'guide_cards',
                'ordering': ['stage', 'role', 'order_no'],
            },
        ),
        migrations.CreateModel(
            name='GuideTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='태스크 제목', max_length=140)),
                ('description', models.TextField(blank=True, help_text='태스크 상세 설명', null=True)),
                ('order_no', models.IntegerField(default=0, help_text='정렬 순서')),
                ('is_required', models.BooleanField(default=True, help_text='필수 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='guides.guidecard')),
            ],
            options={
                'db_table': 'guide_tasks',
                'ordering': ['card', 'order_no'],
            },
        ),
    ]
