# Generated by Django 5.2.10 on 2026-01-30 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guides', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guidetaskprogress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to='projects.project'),
        ),
        migrations.AddField(
            model_name='guidetaskprogress',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='guides.guidetask'),
        ),
        migrations.AddField(
            model_name='guidetaskprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='guidecard',
            index=models.Index(fields=['stage', 'role', 'order_no'], name='guide_cards_stage_i_132d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='guidecard',
            index=models.Index(fields=['is_active'], name='guide_cards_is_acti_e632b4_idx'),
        ),
        migrations.AddIndex(
            model_name='guidetask',
            index=models.Index(fields=['card', 'order_no'], name='guide_tasks_card_id_17746d_idx'),
        ),
        migrations.AddIndex(
            model_name='guidetaskprogress',
            index=models.Index(fields=['project', 'user'], name='guide_task__project_5c19f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='guidetaskprogress',
            constraint=models.UniqueConstraint(fields=('task', 'project', 'user'), name='uq_task_project_user'),
        ),
    ]
