# Generated by Django 5.2.10 on 2026-02-06 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_techstack_user_tech_stacks'),
        ('guides', '0002_initial'),
        ('projects', '0004_remove_project_current_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_tasks', models.IntegerField(default=0, help_text='완료한 태스크 수')),
                ('total_tasks', models.IntegerField(default=0, help_text='전체 태스크 수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_progress',
            },
        ),
        migrations.RemoveField(
            model_name='guidecard',
            name='stage',
        ),
        migrations.AlterModelOptions(
            name='guidecard',
            options={'ordering': ['role', 'order_no']},
        ),
        migrations.RemoveConstraint(
            model_name='guidetaskprogress',
            name='uq_task_project_user',
        ),
        migrations.RemoveIndex(
            model_name='guidecard',
            name='guide_cards_stage_i_132d3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='guidetaskprogress',
            name='guide_task__project_5c19f5_idx',
        ),
        migrations.RemoveField(
            model_name='guidetaskprogress',
            name='user',
        ),
        migrations.AlterField(
            model_name='guidecard',
            name='content_md',
            field=models.TextField(help_text='미션 설명 (마크다운)'),
        ),
        migrations.AlterField(
            model_name='guidecard',
            name='order_no',
            field=models.IntegerField(default=0, help_text='역할별 미션 순서'),
        ),
        migrations.AlterField(
            model_name='guidecard',
            name='title',
            field=models.CharField(help_text='미션 제목', max_length=120),
        ),
        migrations.AlterField(
            model_name='guidetaskprogress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_task_progress', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='guidecard',
            index=models.Index(fields=['role', 'order_no'], name='guide_cards_role_id_05238e_idx'),
        ),
        migrations.AddIndex(
            model_name='guidetaskprogress',
            index=models.Index(fields=['project'], name='guide_task__project_814d38_idx'),
        ),
        migrations.AddIndex(
            model_name='guidetaskprogress',
            index=models.Index(fields=['task'], name='guide_task__task_id_5123d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='guidetaskprogress',
            constraint=models.UniqueConstraint(fields=('task', 'project'), name='uq_task_project'),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_progress', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_progress', to='accounts.role'),
        ),
        migrations.DeleteModel(
            name='GuideStage',
        ),
        migrations.AddConstraint(
            model_name='projectprogress',
            constraint=models.UniqueConstraint(fields=('project', 'role'), name='uq_project_role'),
        ),
    ]
