# Generated by Django 5.2.10 on 2026-02-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_projectprogress_remove_guidecard_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidetask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
