# Generated by Django 5.2.10 on 2026-01-30 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='팀 이름', max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(help_text='연결된 프로젝트 (1:1)', on_delete=django.db.models.deletion.CASCADE, related_name='team', to='projects.project')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='활성 상태 (탈퇴 시 False)')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, help_text='탈퇴 일시', null=True)),
                ('role', models.ForeignKey(help_text='배정된 역할', on_delete=django.db.models.deletion.PROTECT, related_name='team_members', to='accounts.role')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_members',
                'indexes': [models.Index(fields=['team', 'role'], name='team_member_team_id_a23ddb_idx'), models.Index(fields=['user'], name='team_member_user_id_906d63_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'user'), name='uq_team_member')],
            },
        ),
    ]
